# ---- configuration ----

# exclude bundle files
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor
  - Submodules
  - README.md
  - LICENSE
  - CONTRIBUTING.md

timezone: Asia/Tokyo
encording: utf-8

# ---- site vairables ----

title : "ハンドパン筋トレメニュー"

# ---- build option ----

markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: _scss
  style: compressed

# ---- build option ----
collections:
  pages:
    output: true
    permalink: /:path